android-gadget: Fix build problem caused by 3.11-rc merge
Vishal Bhoj pointed out a build issue w/ the Android gadget driver:

drivers/usb/gadget/android.c: In function ‘rndis_function_bind_config’:
drivers/usb/gadget/android.c:599:2: error: too few arguments to function
‘gether_setup_name’
In file included from drivers/usb/gadget/android.c:41:0:
drivers/usb/gadget/u_ether.c:758:17: note: declared here

This adds the tweaks to the android gadget driver that f_rndis and
u_ether now require.

Reported-by: Vishal Bhoj <vishal.bhoj@linaro.org>
Signed-off-by: John Stultz <john.stultz@linaro.org>